login:
  passwordSalt: caojiantao
  tokenSalt: chenlisha
  domain: caojiantao.site

spring:
  application:
    name: taotao_tool
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taotao-tool
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
