login:
  passwordSalt: caojiantao
  tokenSalt: chenlisha
  domain: caojiantao.site

upload:
  image:
    path: /var/www/image
    quality: 0.5

spring:
  application:
    name: taotao_tool
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taotao-tool
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

love-note:
  app-id: wx781e612a7639f187
  app-secret: 9677d9c7750b5182241f1675dca82484
  tokenSalt: chenlisha

carpool:
  app-id:
  app-secret:
  tokenSalt:
