pic:
  path: D:/tmp/pic
video:
  path: D:/tmp/video

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      # 兼容 swagger3 空指针问题
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taotao-tool
    username: root
    password: 123456
  web:
    resources:
      static-locations: file:${pic.path}

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
