upload:
  thumb:
    path: thumbnail
    quality: 0.4

login:
  redirectUrl: https://www.baidu.com
  passwordSalt: caojiantao
  tokenSalt: chenlisha

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    pathmatch:
      # 兼容 swagger3 空指针问题
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/taotao-tool
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
